run:
  deadline: 10m
  modules-download-mode: vendor
  issues.exclude-dirs:
    - swagger

linters:
  enable-all: false
  enable:
    - dupl
    - errcheck
    - goconst
    - gofmt
    - revive
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unconvert
    - unused

issues:
  max-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl # Excluding duplicate code check in tests as test code can be verbose
    - path: _test.go
      linters:
        - revive
      text: "unused-parameter:"
    - path: mock.go
      linters:
        - revive
      text: "unused-parameter:"
